const fourChampRewardLevels = [280, 300, 320, 340, 350, 360];
const threeChampRewardLevels = [183, 223, 265];
const twoChampRewardLevels = [99, 115, 127];

const fiveStarChars = [
  {
    name: 'Black Bolt',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Medusa'
  },
  {
    name: 'Black Panther (Civil War)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Black Panther'
  },
  {
    name: 'Black Widow',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Black Widow'
  },
  {
    name: 'Captain America (The First Avenger)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Peggy Carter'
  },
  {
    name: 'Captain America (Infinity War)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Winter Soldier'
  },
  {
    name: 'Daredevil',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Kingpin'
  },
  {
    name: 'Doctor Octopus',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Carnage'
  },
  {
    name: 'Ghost Rider',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Ghost Rider'
  },
  {
    name: 'Green Goblin',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Sandman'
  },
  {
    name: 'Hawkeye',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Kate Bishop'
  },
  {
    name: 'Iron Man',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'War Machine'
  },
  {
    name: 'Jean Grey',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Jubilee'
  },
  {
    name: 'Jessica Jones',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'America Chavez'
  },
  {
    name: 'Loki',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'The Hulk (Main Event)'
  },
  {
    name: 'Okoye',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Shuri'
  },
  {
    name: 'Silver Surfer',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Mr. Fantastic'
  },
  {
    name: 'Spider-Man (Back In Black)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Spider-Man (Infinity War)'
  },
  {
    name: 'Spider-Man (Peter Parker)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Vulture'
  },
  {
    name: 'Star-Lord',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Drax'
  },
  {
    name: 'Thanos',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Gamora'
  },
  {
    name: 'Thor',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Valkyrie'
  },
  {
    name: 'Wasp',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Ant-Man'
  },
  {
    name: 'Wolverine (Old Man Logan)',
    pic: 'someurl.com',
    powerOne: 0,
    powerTwo: 0,
    powerThree: 0,
    totalPowerLevel: 0,
    characterLevel: 255,
    powerOneColor: 'green',
    powerTwoColor: 'black',
    powerThreeColor: 'yellow',
    feeder: 'Wolverine (X-Force)'
  }
];

const fourStarChars = [];

const threeStarChars = [];

const twoStarChars = [];